backend:
  name: git-gateway
  branch: master


media_folder: "static/assets/uploads"
public_folder: "/assets/uploads"

collections:
  - name: "coding"
  label: "Coding"
  folder: "content/coding"
  create: true
  slug: "{{year}}-{{slug}}"
  fields:
    - {label: "Title", name: "title", widget: "string", required: true}