# main menu
[[main]]
name = "Home"
url = ""
weight = 1

[[main]]
name = "Features"
url = "about/"
weight = 2

[[main]]
name = "Pricing"
url = "blog/"
weight = 3

[[main]]
name = "Showcase"
url = "contact/"
weight = 5

[[main]]
name = "Marketplace"
url = "contact/"
weight = 5

[[main]]
name = "Academy"
url = "contact/"
weight = 5


# footer menu
[[footer]]
name = "About"
url = "about/"
weight = 1

[[footer]]
name = "Blog"
url = "blog/"
weight = 2

[[footer]]
name = "Blog Details"
url = "blog/post-1/"
weight = 3

[[footer]]
name = "Terms & Conditions"
url = "terms-and-conditions/"
weight = 4