# main menu


[[main]]
name = "Features"
url = "features/"
weight = 2

[[main]]
name = "Pricing"
url = "pricing/"
weight = 3

[[main]]
name = "Showcase"
url = "showcase/"
weight = 4

[[main]]
name = "Marketplace"
url = "marketplace/"
weight = 5

[[main]]
name = "Tutorial"
url = "tutorial/"
weight = 6

[[main]]
name = "Sign in"
url = "signin/"
weight = 7


# footer menu
[[footer]]
name = "Features"
url = "features/"
weight = 2

[[footer]]
name = "Pricing"
url = "pricing/"
weight = 3

[[footer]]
name = "Showcase"
url = "showcase/"
weight = 4