#################### default parameters ################################
# favicon
favicon = "images/favicon.png"
# logo
logo = "images/FloFrameLogo.png"
# use `x` with logo_width, example: "100x"
logo_width = "240x"
# logo text will only show when logo is missing.
logo_text = "Andromeda"
# OpenGraph / Twitter Card metadata
description = "This is meta description"
author = "Themefisher"
image = "images/logo.png"                # this image will be used as fallback if a page has no image of its own

# footer information
footer_info = "Cotham Technologies is an innovative software company that reinvents app development through its patent-pending FloFrame technology, the only no-code platform that delivers native app solutions. FloPro, powered by FloFrame, is a breakthrough product that transforms the app build process, rapidly delivering high impact user-centric experiences, without compromising on performance and usability. FloPro creates a new frontier in mobile app development, empowering enterprises to accelerate digital transformations by integrating seamlessly with existing and future data sources, increasing app throughput, and shortening time to market."

# contact form action
contact_form_action = "https://formspree.io/f/xgernlzd" # contact form works with https://formspree.io

# copyright
copyright = "© Copyright 2012 - 2022 | Cotham Technologies Ltd | All Rights Reserved"
# custom script on header, example: custom_script= "<script>console.log(\"Hello World\")</script>" 
custom_script = ""

# buy premium popup
buy_premium_popup = true

# Main Sections
mainSections = ["blog"]

# reading time for blog posts
reading_time = true

# contact information
[contact_info]
address = "2118 Thornridge Cir. Syracuse, Connecticut 35624"
phone = "+44 117 405 7336"
email = "["info@cothamtechnologies.com", "smith@anderson.io", "john@anderson.io"]"

# imaging processing
[imaging]
# Default JPEG or WebP quality setting. Default is 100.
quality = 100

# Preloader
[preloader]
enable = true
preloader = "images/favicon.png" # use jpg, png, svg or gif format.

# Navigation button
[navigation_button]
enable = true
label = "get started"
link = "https://gethugothemes.com/products/andromeda/"

# cookies
[cookies]
enable = false
expire_days = 2
content = "This site uses cookies. By continuing to use this website, you agree to their use."
button = "I Accept"

# call-to-action
[cta]
enable = true
title = "Get Andromeda-Premium Now"
content = "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Morbi egestas <br> Werat viverra id et aliquet. vulputate egestas sollicitudin."
button = "Download The Theme"
button_link = "https://gethugothemes.com/products/andromeda/"

############################# social site ########################
[[social]]
title = "Andromeda"
icon = "lab la-facebook-f" # https://icons8.com/line-awesome
link = "https://en-gb.facebook.com/cothamtechnologies/"

[[social]]
title = "AndromedaTweet"
icon = "lab la-twitter"  # https://icons8.com/line-awesome
link = "https://twitter.com/CothamTech"

[[social]]
title = "AndromedaIn"
icon = "lab la-linkedin-in" # https://icons8.com/line-awesome
link = "https://www.linkedin.com/company/11183689/"

[[social]]
title = "AndromedaPin"
icon = "lab la-pinterest" # https://icons8.com/line-awesome
link = "#!"
